# Changes here will be overwritten by Copier
_commit: 2d0c192
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: python-project-templates
project_description: Hatch plugin for Rust
project_name: hatch rust
python_version_primary: '3.11'
team: the hatch-rust authors
